// Shared boot for every unit's slides.
//
// Keys, in addition to reveal's own (arrows, Esc for overview, F fullscreen):
//   N   show / hide the notes panel beside the slide (remembered)
//   R   reading mode: every slide stacked in one page, notes beside each
//   D   toggle dark / light
//   G   the unit's glossary, searchable; click a term to jump to its slide
//   M   back to the menu, the site's index.html listing every unit
//
// Terms: <span class="term">facets</span>, or <span class="term" data-term="tight row">tight</span>
// when the words on the slide differ from the glossary entry. Clicking one opens its
// definition. Definitions come from the unit's glossary.js, built from GLOSSARY.org by
// `co slides` / `co glossary`; this file loads it, so decks need no extra script tag.
//
// (No speaker-window plugin: reveal 5.1.0's notes plugin from cdnjs throws on
// load and aborts initialisation. N and R cover the same need.)
//
// URL switches, handy for bookmarks and screenshots: ?view=read, ?notes=1.
//
// Math is written as $...$ inline and $$...$$ display; KaTeX renders it once,
// before reveal lays the slides out, so slide sizes are measured correctly.

(function () {
  const store = {
    get(k) { try { return localStorage.getItem(k); } catch (_) { return null; } },
    set(k, v) { try { localStorage.setItem(k, v); } catch (_) { /* private mode */ } },
  };

  const params = new URLSearchParams(location.search);
  const reading = params.get("view") === "read";

  const theme = store.get("co-theme");
  if (theme) document.documentElement.setAttribute("data-theme", theme);

  function renderMath() {
    if (!window.renderMathInElement) return;
    renderMathInElement(document.querySelector(".reveal"), {
      delimiters: [
        { left: "$$", right: "$$", display: true },
        { left: "$", right: "$", display: false },
      ],
      ignoredTags: ["script", "noscript", "style", "textarea", "pre", "code"],
      throwOnError: false,
    });
  }

  function toggleDark() {
    const root = document.documentElement;
    const dark = root.getAttribute("data-theme") === "dark" ||
      (!root.hasAttribute("data-theme") && matchMedia("(prefers-color-scheme: dark)").matches);
    const next = dark ? "light" : "dark";
    root.setAttribute("data-theme", next);
    store.set("co-theme", next);
  }

  // The menu is generated by slides/site/build.py, so it exists only in a built site.
  // A deck opened straight from the source tree goes to the local build in _site/.
  function toMenu() {
    const built = location.protocol !== "file:" || location.pathname.includes("/_site/");
    location.href = new URL(built ? "../../index.html" : "../../_site/index.html", location.href).toString();
  }

  function toggleReading() {
    const url = new URL(location.href);
    if (reading) url.searchParams.delete("view"); else url.searchParams.set("view", "read");
    url.hash = "";
    location.href = url.toString();
  }

  function help(text) {
    const el = document.createElement("div");
    el.className = "deck-help";
    el.innerHTML = text;
    document.body.appendChild(el);
  }

  // ---------------------------------------------------------------- glossary
  // Slide titles are read before KaTeX renders, while math is still source text, so
  // they compare cleanly with the titles the glossary names.
  const titleKey = (t) => t.toLowerCase().replace(/\\[a-z]+/g, "").replace(/[^0-9a-z]/g, "");
  const slideTitles = Array.from(document.querySelectorAll(".reveal .slides > section")).map((s) => {
    const h = s.querySelector("h2");
    return h ? titleKey(h.textContent) : "";
  });
  // A term's words are read now, before KaTeX turns "$I(x)$" into rendered markup.
  document.querySelectorAll(".reveal .term:not([data-term])").forEach((t) => { t.dataset.term = t.textContent; });
  const termKey = (t) => t.replace(/\\\(|\\\)|\$/g, "").replace(/\s+/g, " ").trim().toLowerCase();

  function lookup(ref) {
    const entries = window.GLOSSARY || [];
    const k = termKey(ref);
    const exact = entries.find((e) => e.keys[0] === k);
    if (exact) return exact;
    for (const cand of [k, k.replace(/es$/, ""), k.replace(/s$/, "")]) {
      const hit = entries.find((e) => e.keys.includes(cand));
      if (hit) return hit;
    }
    return null;
  }

  function renderInline(el) {
    if (!window.renderMathInElement) return;
    renderMathInElement(el, {
      delimiters: [{ left: "\\(", right: "\\)", display: false }, { left: "$", right: "$", display: false }],
      throwOnError: false,
    });
  }

  function goToSlide(title) {
    const i = slideTitles.indexOf(titleKey(title));
    if (i < 0) return false;
    closePop();
    closeIndex();
    if (reading) location.hash = "#s" + (i + 1); else Reveal.slide(i);
    return true;
  }

  function slideLink(entry) {
    if (!entry.slide || slideTitles.indexOf(titleKey(entry.slide)) < 0) return "";
    return `<button class="gl-go" type="button">slide: ${entry.slide.replace(/</g, "&lt;")} →</button>`;
  }

  let pop = null;
  function closePop() { if (pop) { pop.remove(); pop = null; } }

  function openPop(termEl) {
    closePop();
    const ref = termEl.dataset.term || termEl.textContent;
    const entry = lookup(ref);
    pop = document.createElement("div");
    pop.className = "gl-pop";
    pop.setAttribute("role", "dialog");
    pop.innerHTML = entry
      ? `<div class="gl-term">${entry.term_html}</div><div class="gl-def">${entry.html}</div>` +
        `<div class="gl-foot">${slideLink(entry)}<span class="gl-hint"><kbd>G</kbd> all terms</span></div>`
      : `<div class="gl-def">No glossary entry for “${ref}”.</div>`;
    document.body.appendChild(pop);
    renderInline(pop);
    const go = pop.querySelector(".gl-go");
    if (go) go.addEventListener("click", () => goToSlide(entry.slide));
    const r = termEl.getBoundingClientRect();
    const w = pop.offsetWidth, h = pop.offsetHeight;
    const left = Math.max(12, Math.min(r.left, innerWidth - w - 12));
    const below = r.bottom + 8 + h < innerHeight - 12;
    pop.style.left = left + "px";
    pop.style.top = (below ? r.bottom + 8 : Math.max(12, r.top - h - 8)) + "px";
  }

  let index = null;
  function closeIndex() { if (index) { index.remove(); index = null; } }

  function openIndex() {
    closePop();
    if (index) { closeIndex(); return; }
    const entries = window.GLOSSARY || [];
    index = document.createElement("div");
    index.className = "gl-index";
    index.innerHTML =
      `<div class="gl-index-head"><input type="search" placeholder="filter ${entries.length} terms" ` +
      `aria-label="filter terms"><span class="gl-hint"><kbd>Esc</kbd> close</span></div><div class="gl-list"></div>`;
    const list = index.querySelector(".gl-list");
    let section = null;
    for (const e of entries) {
      if (e.section !== section) {
        section = e.section;
        const h = document.createElement("h4");
        h.textContent = section;
        list.appendChild(h);
      }
      const item = document.createElement("div");
      item.className = "gl-item";
      item.dataset.search = (e.keys.join(" ") + " " + e.html.replace(/<[^>]+>/g, "")).toLowerCase();
      item.innerHTML = `<div class="gl-term">${e.term_html}</div><div class="gl-def">${e.html}</div>${slideLink(e)}`;
      const go = item.querySelector(".gl-go");
      if (go) go.addEventListener("click", () => goToSlide(e.slide));
      list.appendChild(item);
    }
    if (!entries.length) list.textContent = "This unit has no glossary.js yet: run `uv run co glossary`.";
    document.body.appendChild(index);
    renderInline(list);
    const input = index.querySelector("input");
    input.addEventListener("input", () => {
      const q = input.value.trim().toLowerCase();
      list.querySelectorAll(".gl-item").forEach((it) => { it.hidden = q && !it.dataset.search.includes(q); });
      list.querySelectorAll("h4").forEach((h) => {
        let n = h.nextElementSibling, any = false;
        while (n && n.tagName !== "H4") { if (!n.hidden) any = true; n = n.nextElementSibling; }
        h.hidden = !any;
      });
    });
    // Focus after this keypress has been delivered, or the G lands in the filter box.
    setTimeout(() => input.focus(), 0);
  }

  document.addEventListener("click", (e) => {
    const t = e.target.closest(".term");
    if (t) { e.preventDefault(); openPop(t); return; }
    if (pop && !e.target.closest(".gl-pop")) closePop();
    if (index && !e.target.closest(".gl-index")) closeIndex();
  });
  // Capture phase, so Esc closes a popover before reveal opens its overview.
  window.addEventListener("keydown", (e) => {
    if (e.key === "Escape" && (pop || index)) {
      closePop(); closeIndex();
      e.stopImmediatePropagation(); e.preventDefault();
    }
  }, true);

  const glossaryScript = document.createElement("script");
  glossaryScript.src = "glossary.js";
  document.head.appendChild(glossaryScript);

  renderMath();

  // ---------------------------------------------------------------- reading
  if (reading) {
    document.body.classList.add("reading");
    const slides = document.querySelector(".reveal .slides");
    let n = 0;
    for (const section of Array.from(slides.children)) {
      if (section.tagName !== "SECTION") continue;
      n += 1;
      const wrap = document.createElement("article");
      wrap.className = "read-slide";
      wrap.id = "s" + n;
      const frame = document.createElement("div");
      frame.className = "read-frame";
      const notes = section.querySelector(":scope > aside.notes");
      section.parentNode.insertBefore(wrap, section);
      frame.appendChild(section);
      wrap.appendChild(frame);
      const side = document.createElement("div");
      side.className = "read-notes";
      side.innerHTML = `<a class="read-no" href="#s${n}">${n}</a>`;
      if (notes) side.appendChild(notes);
      wrap.appendChild(side);
    }
    if (window.RevealHighlight) {
      const hl = RevealHighlight();
      if (hl.hljs) document.querySelectorAll("pre code").forEach((el) => hl.hljs.highlightElement(el));
    }
    help("<kbd>R</kbd> back to slides &nbsp; <kbd>G</kbd> glossary &nbsp; <kbd>D</kbd> dark &nbsp; <kbd>M</kbd> menu");
    document.addEventListener("keydown", (e) => {
      if (e.target.closest("input, textarea")) return;
      if (e.key === "r" || e.key === "R") toggleReading();
      if (e.key === "d" || e.key === "D") toggleDark();
      if (e.key === "g" || e.key === "G") openIndex();
      if (e.key === "m" || e.key === "M") toMenu();
    });
    return;
  }

  // ---------------------------------------------------------------- slides
  help("<kbd>N</kbd> notes &nbsp; <kbd>R</kbd> reading mode &nbsp; <kbd>G</kbd> glossary &nbsp; " +
    "<kbd>D</kbd> dark &nbsp; <kbd>M</kbd> menu &nbsp; <kbd>Esc</kbd> overview");

  Reveal.initialize({
    hash: true,
    width: 1280,
    height: 760,
    margin: 0.05,
    center: false,
    slideNumber: "c/t",
    transition: "none",
    backgroundTransition: "none",
    showNotes: params.get("notes") === "1" || store.get("co-notes") === "1",
    pdfSeparateFragments: false,
    plugins: [RevealHighlight],
    keyboard: {
      78: () => {                                   // N
        const on = !Reveal.getConfig().showNotes;
        Reveal.configure({ showNotes: on });
        store.set("co-notes", on ? "1" : "0");
      },
      82: toggleReading,                            // R
      68: toggleDark,                               // D
      71: openIndex,                                // G
      77: toMenu,                                   // M
    },
  });
  Reveal.on("slidechanged", () => { closePop(); closeIndex(); });

  // ?check=1 — an authoring aid: visit every slide, then cover the page with a list of
  // equations wider than their column and slides taller than the frame.
  if (params.get("check") === "1") {
    Reveal.on("ready", () => {
      const problems = [];
      Reveal.getSlides().forEach((section, i) => {
        Reveal.slide(i);
        section.querySelectorAll(".katex-display").forEach((el) => {
          if (el.scrollWidth > el.clientWidth + 1)
            problems.push(`slide ${i + 1}: equation ${el.scrollWidth}px in ${el.clientWidth}px`);
        });
        section.querySelectorAll(".cols > *, pre, table").forEach((el) => {
          if (el.scrollWidth > el.clientWidth + 4 && !el.closest(".katex-display"))
            problems.push(`slide ${i + 1}: ${el.tagName.toLowerCase()} ${el.scrollWidth}px in ${el.clientWidth}px`);
        });
        if (!section.classList.contains("divider") && section.scrollHeight > Reveal.getConfig().height + 1)
          problems.push(`slide ${i + 1}: content ${section.scrollHeight}px tall`);
      });
      Reveal.slide(0);
      const report = document.createElement("pre");
      report.className = "deck-check";
      report.textContent = problems.length ? problems.join("\n") : "no overflow";
      report.style.cssText = "position:fixed;inset:0;z-index:99;margin:0;padding:40px;" +
        "background:#fff;color:#000;font:20px/1.5 monospace";
      document.body.appendChild(report);
    });
  }
})();
